name: Comment Artifacts
on:
  workflow_run:
    workflows: [Build Docs]
    types: [completed]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  artifacts-url-comments:
    name: Add artifact link to PR comments
    runs-on: ubuntu-latest
    steps:
        - name: Create comment
          uses: marocchino/sticky-pull-request-comment@v2
          with:
            recreate: true
            message: |
              ${{ steps.update.outputs }}
        - name: Update comment with artifact
          id: update
          uses: tonyhallett/artifacts-url-comments@v1.1.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            prefix: Click below to download the docs artifacts
            suffix: (zip file)
            format: name
            addTo: pull
