name: Build Docs

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - docs
  workflow_dispatch:

jobs:
  build-and-upload-artifact:
    name: Build & Upload Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Check out code + LFS with cache
        uses: nschloe/action-cached-lfs-checkout@v1
        # See discussion at https://github.com/actions/checkout/issues/165
        # This is a bundling of the pattern in this comment:
        # https://github.com/actions/checkout/issues/165#issuecomment-657673315

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - uses: tlambert03/setup-qt-libs@v1

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[docs]"

      - name: Build Docs
        uses: GabrielBB/xvfb-action@v1
        env:
          GOOGLE_CALENDAR_ID: ${{ secrets.GOOGLE_CALENDAR_ID }}
          GOOGLE_CALENDAR_API_KEY: ${{ secrets.GOOGLE_CALENDAR_API_KEY }}
        with:
          run: make docs

      # TODO: enable when the link check passes
      # - name: LinkCheck
      #  run: make linkcheck-files

      - name: Upload artifact
        id: upload
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs/_build
      - name: Retrieve artifact url
        id: url
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::set-output name=DOCS_URL::$(curl -v -H "Authorization: token $GITHUB_TOKEN" -s https://api.github.com/repos/melissawm/napari/actions/artifacts | jq '[.artifacts[] | {name : .name, archive_download_url : .archive_download_url} | select (.name == "docs") .archive_download_url][0]')"
      - name: Create comment
        uses: marocchino/sticky-pull-request-comment@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          recreate: true
          message: |
            debug: ${{ steps.url.outputs.DOCS_URL }}
            Latest docs artifact: [docs.zip](${{ steps.url.outputs.DOCS_URL }}) (${{github.event.pull_request.head.sha}})

